spring:
  data:
    mongodb:
      authentication-database: morphia
      database: morphia
      username: morphia
      password: morphia
      port: 0
      uri: mongodb://morphia:morphia@localhost
logging:
  level:
    root: info
    com.jipasoft: debug
    de.flapdoodle.embed.mongo: debug